# SAMI 8.) The program adds the right score value to the user data.

# AFTER FLIGHTS ARE DONE, CALL THE FOLLOWING FUNCTION BELOW

def highScore():
    # COMMAND TO COUNT TOTAL FLIGHTS TO COUNTRIES
    # COMMAND TO COUNT TOTAL VALUE FOR THE FLIGHTS DONE
    # COMMAND TO RETURN VALUE (HIGHSCORE) FROM THE FUNCTION

#IN THE END OF THE CODE, AFTER GETTING HIGHSCORE FROM FUNCTION --> COMMAND TO PUSH THE HIGHSCORE INTO THE GAME USERS DATA




if countryselecting



